version: "3.7"

services:
  postgres:
    build:
      context:
        postgres/
    env_file: 
       .env
    ports:
      - 5432:5432
    volumes:
      - mental_maths_volume:/var/lib/postgresql/data
  cron:
    build:
      context:
        backup/        
    env_file: 
       .env

volumes:
  mental_maths_volume:
